services:
  services-person-traffic-1:
    # build: # <---- IF BUILDING IMAGE
    #   context: .
    #   dockerfile: Dockerfile
    image: in-out-counting-services-person-counter
    container_name: services-traffic-counter
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    runtime: nvidia
    shm_size: 1gb
    command: >
      sh -c "pip install paho-mqtt && python main.py"


# DUPLICATE CONTAINER
  # services-traffic-traffic-2:
  #   image: in-out-counting-services-person-counter
  #   container_name: services-traffic-counter-2
  #   restart: unless-stopped
  #   env_file:
  #     - env_2
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   shm_size: 1gb
  #   command: >
  #     sh -c "pip install paho-mqtt ffmpeg-python && python main.py"

  # services-traffic-counter-3:
  #   image: in-out-counting-services-person-counter
  #   container_name: services-traffic-counter-3
  #   restart: unless-stopped
  #   env_file:
  #     - env_3
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   shm_size: 1g
  #   command: >
  #     sh -c "pip install paho-mqtt && python main.py"
  