services:
  # services-python-1:
  #   # build:
  #   #   context: .
  #   #   dockerfile: Dockerfile
  #   image: python-mini-v3:latest
  #   container_name: services-python-1
  #   restart: unless-stopped
  #   env_file:
  #     - .env_b1
  #   volumes:
  #     - .:/app
  #   command: >
  #     sh -c "pip install -q -r /app/requirements.txt && python /app/main.py"
  #   runtime: nvidia
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - envisions
  #   shm_size: 1gb
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, video]

  # services-python-2:
  #   image: python-mini-v3:latest
  #   container_name: services-python-2
  #   restart: unless-stopped
  #   env_file:
  #     - .env_b2s
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - envisions
  #   shm_size: 1gb
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, video]

  # services-python-3:
  #   image: python-mini-v3:latest
  #   container_name: services-python-3
  #   restart: unless-stopped
  #   env_file:
  #     - .env_b2u
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - envisions
  #   shm_size: 1gb
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, video]

  # services-python-4:
  #   image: python-mini-v3:latest
  #   container_name: services-python-4
  #   restart: unless-stopped
  #   env_file:
  #     - .env_b3s
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - envisions
  #   shm_size: 1gb
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, video]

  # services-python-5:
  #   image: python-mini-v3:latest
  #   container_name: services-python-5
  #   restart: unless-stopped
  #   env_file:
  #     - .env_b3u
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - envisions
  #   shm_size: 1gb
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, video]

  services-python-6:
    image: python-mini-v3:latest
    container_name: services-python-6
    restart: unless-stopped
    env_file:
      - .env_s21
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envisions
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  services-python-7:
    image: python-mini-v3:latest
    container_name: services-python-7
    restart: unless-stopped
    env_file:
      - .env_s24
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envisions
    shm_size: 1gb
    deploy:
      resources:
        reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu, video]

  services-python-8:
    image: python-mini-v3:latest
    container_name: services-python-8
    restart: unless-stopped
    env_file:
      - .env_s27
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envisions
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  services-python-9:
    image: python-mini-v3:latest
    container_name: services-python-9
    restart: unless-stopped
    env_file:
      - .env_u2
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envisions
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  services-python-10:
    image: python-mini-v3:latest
    container_name: services-python-10
    restart: unless-stopped
    env_file:
      - .env_u7
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envisions
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  services-python-11:
    image: python-mini-v3:latest
    container_name: services-python-11
    restart: unless-stopped
    env_file:
      - .env_u9
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envisions
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  services-python-12:
    image: python-mini-v3:latest
    container_name: services-python-12
    restart: unless-stopped
    env_file:
      - .env_u12
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envisions
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  # services-python-13:
  #   image: python-mini-v3:latest
  #   container_name: services-python-13
  #   restart: unless-stopped
  #   env_file:
  #     - .env_u38
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - envisions
  #   shm_size: 1gb
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, video]

  # services-python-14:
  #   image: python-mini-v3:latest
  #   container_name: services-python-14
  #   restart: unless-stopped
  #   env_file:
  #     - .env_u39
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - envisions
  #   shm_size: 1gb
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu, video]

networks:
  envisions:
    driver: bridge



# DUPLICATE CONTAINER
  # services-traffic-traffic-2:
  #   image: in-out-counting-services-python-0
  #   container_name: services-traffic-counter-2
  #   restart: unless-stopped
  #   env_file:
  #     - env_2
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   shm_size: 1gb
  #   command: >
  #     sh -c "pip install paho-mqtt ffmpeg-python && python main.py"

  # services-traffic-counter-3:
  #   image: in-out-counting-services-python-0
  #   container_name: services-traffic-counter-3
  #   restart: unless-stopped
  #   env_file:
  #     - env_3
  #   volumes:
  #     - .:/app
  #   runtime: nvidia
  #   shm_size: 1g
  #   command: >
  #     sh -c "pip install paho-mqtt && python main.py"
  
